In [1]:
!pip install pandas scikit-learn joblib

Access is denied.

In [2]:
import pandas, sklearn, joblib
print("pandas:", pandas.__version__)
print("sklearn:", sklearn.__version__)
print("joblib:", joblib.__version__)

pandas: 2.2.3
sklearn: 1.6.1
joblib: 1.4.2

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
import joblib
from pathlib import Path

Path("../backend/models").mkdir(parents=True, exist_ok=True)

In [4]:
# INTENT MODEL
intent_df = pd.read_csv("../data/intent_dataset.csv")
X_train, X_test, y_train, y_test = train_test_split(
    intent_df["text"], intent_df["intent"],
    test_size=0.2, random_state=42, stratify=intent_df["intent"]
)

intent_model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=1)),
    ("clf", LinearSVC())
])
intent_model.fit(X_train, y_train)
pred = intent_model.predict(X_test)
print("INTENT REPORT:\n", classification_report(y_test, pred))
joblib.dump(intent_model, "../backend/models/intent_model.joblib")

INTENT REPORT:
               precision    recall  f1-score   support

check_answer       1.00      1.00      1.00         1
     explain       0.75      1.00      0.86         3
    greeting       1.00      1.00      1.00         2
       other       0.00      0.00      0.00         1
        quiz       1.00      1.00      1.00         2
   recommend       1.00      1.00      1.00         1

    accuracy                           0.90        10
   macro avg       0.79      0.83      0.81        10
weighted avg       0.82      0.90      0.86        10

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

['../backend/models/intent_model.joblib']

In [6]:
print(classification_report(y_test, pred, zero_division=0))

              precision    recall  f1-score   support

check_answer       1.00      1.00      1.00         1
     explain       0.75      1.00      0.86         3
    greeting       1.00      1.00      1.00         2
       other       0.00      0.00      0.00         1
        quiz       1.00      1.00      1.00         2
   recommend       1.00      1.00      1.00         1

    accuracy                           0.90        10
   macro avg       0.79      0.83      0.81        10
weighted avg       0.82      0.90      0.86        10

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
import joblib
from pathlib import Path

Path("../backend/models").mkdir(parents=True, exist_ok=True)

topic_df = pd.read_csv("../data/topic_dataset.csv")

X_train, X_test, y_train, y_test = train_test_split(
    topic_df["text"], topic_df["topic"],
    test_size=0.2, random_state=42, stratify=topic_df["topic"]
)

topic_model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=1)),
    ("clf", LinearSVC())
])

topic_model.fit(X_train, y_train)
pred = topic_model.predict(X_test)

print("TOPIC REPORT:\n", classification_report(y_test, pred, zero_division=0))

joblib.dump(topic_model, "../backend/models/topic_model.joblib")
print("✅ Saved: ../backend/models/topic_model.joblib")

ValueError: The test_size = 6 should be greater or equal to the number of classes = 13

In [8]:
import pandas as pd
import random
from pathlib import Path

random.seed(42)

topics = [
    "SDLC","Agile Model","Scrum","UML","Use Case Diagram","Class Diagram",
    "Sequence Diagram","Software Testing","Unit Testing","Integration Testing",
    "System Testing","Version Control","Software Maintenance"
]

templates = [
    "Explain {t}",
    "What is {t}?",
    "Define {t}",
    "Give an example of {t}",
    "Why is {t} important?",
    "Advantages of {t}",
    "Disadvantages of {t}",
    "When do we use {t}?",
    "Summarize {t}",
    "Key features of {t}"
]

rows = []
for t in topics:
    for temp in templates:
        rows.append((temp.format(t=t), t))

df = pd.DataFrame(rows, columns=["text","topic"]).drop_duplicates()
Path("../data").mkdir(parents=True, exist_ok=True)
df.to_csv("../data/topic_dataset.csv", index=False)

print("✅ Rebuilt topic_dataset.csv with rows:", len(df))
df.head(10)

✅ Rebuilt topic_dataset.csv with rows: 130

                      text topic
0             Explain SDLC  SDLC
1            What is SDLC?  SDLC
2              Define SDLC  SDLC
3  Give an example of SDLC  SDLC
4   Why is SDLC important?  SDLC
5       Advantages of SDLC  SDLC
6    Disadvantages of SDLC  SDLC
7     When do we use SDLC?  SDLC
8           Summarize SDLC  SDLC
9     Key features of SDLC  SDLC

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
import joblib
from pathlib import Path

Path("../backend/models").mkdir(parents=True, exist_ok=True)

topic_df = pd.read_csv("../data/topic_dataset.csv")

X_train, X_test, y_train, y_test = train_test_split(
    topic_df["text"], topic_df["topic"],
    test_size=0.2, random_state=42, stratify=topic_df["topic"]
)

topic_model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=1)),
    ("clf", LinearSVC())
])

topic_model.fit(X_train, y_train)
pred = topic_model.predict(X_test)

print("=== TOPIC MODEL REPORT ===")
print(classification_report(y_test, pred, zero_division=0))

joblib.dump(topic_model, "../backend/models/topic_model.joblib")
print("✅ Saved: ../backend/models/topic_model.joblib")

=== TOPIC MODEL REPORT ===
                      precision    recall  f1-score   support

         Agile Model       1.00      1.00      1.00         2
       Class Diagram       1.00      1.00      1.00         2
 Integration Testing       1.00      1.00      1.00         2
                SDLC       1.00      1.00      1.00         2
               Scrum       1.00      1.00      1.00         2
    Sequence Diagram       1.00      1.00      1.00         2
Software Maintenance       1.00      1.00      1.00         2
    Software Testing       1.00      1.00      1.00         2
      System Testing       1.00      1.00      1.00         2
                 UML       1.00      1.00      1.00         2
        Unit Testing       1.00      1.00      1.00         2
    Use Case Diagram       1.00      1.00      1.00         2
     Version Control       1.00      1.00      1.00         2

            accuracy                           1.00        26
           macro avg       1.00      1.00      1.00        26
        weighted avg       1.00      1.00      1.00        26

✅ Saved: ../backend/models/topic_model.joblib

In [11]:
=== TOPIC MODEL REPORT ===
                      precision    recall  f1-score   support

         Agile Model       1.00      1.00      1.00         2
       Class Diagram       1.00      1.00      1.00         2
 Integration Testing       1.00      1.00      1.00         2
                SDLC       1.00      1.00      1.00         2
               Scrum       1.00      1.00      1.00         2
    Sequence Diagram       1.00      1.00      1.00         2
Software Maintenance       1.00      1.00      1.00         2
    Software Testing       1.00      1.00      1.00         2
      System Testing       1.00      1.00      1.00         2
                 UML       1.00      1.00      1.00         2
        Unit Testing       1.00      1.00      1.00         2
    Use Case Diagram       1.00      1.00      1.00         2
     Version Control       1.00      1.00      1.00         2

            accuracy                           1.00        26
           macro avg       1.00      1.00      1.00        26
        weighted avg       1.00      1.00      1.00        26

✅ Saved: ../backend/models/topic_model.joblib

IndentationError: unindent does not match any outer indentation level (<string>, line 4)

In [12]:
import json
import joblib
from pathlib import Path

# ensure models folder exists
Path("../backend/models").mkdir(parents=True, exist_ok=True)

def export_linear_svc_pipeline(joblib_path, out_json_path):
    pipe = joblib.load(joblib_path)

    tfidf = pipe.named_steps["tfidf"]
    clf = pipe.named_steps["clf"]

    payload = {
        "ngram_range": list(tfidf.ngram_range),
        "lowercase": tfidf.lowercase,
        "vocabulary_": tfidf.vocabulary_,
        "idf_": tfidf.idf_.tolist(),
        "classes_": clf.classes_.tolist(),
        "coef_": clf.coef_.tolist(),
        "intercept_": clf.intercept_.tolist()
    }

    with open(out_json_path, "w", encoding="utf-8") as f:
        json.dump(payload, f)

# export intent model
export_linear_svc_pipeline(
    "../backend/models/intent_model.joblib",
    "../backend/models/intentModel.json"
)

# export topic model
export_linear_svc_pipeline(
    "../backend/models/topic_model.joblib",
    "../backend/models/topicModel.json"
)

print("Export complete.")

Export complete.

In [1]:
import pandas as pd
from pathlib import Path
import random

# ✅ Topics (use same spelling everywhere)
TOPICS = [
  "SDLC",
  "Agile Model",
  "Scrum",
  "UML",
  "Use Case Diagram",
  "Class Diagram",
  "Sequence Diagram",
  "Software Testing",
  "Unit Testing",
  "Integration Testing",
  "System Testing",
  "Version Control",
  "Software Maintenance"
]

# ✅ Create backend/data folder if not exists
Path("../backend/data").mkdir(parents=True, exist_ok=True)

print("OK - setup done. Topics:", len(TOPICS))

OK - setup done. Topics: 13

In [2]:
lesson_bank = {
 "SDLC": [
  "SDLC (Software Development Life Cycle) is a structured process for building software. Typical phases: requirements, design, implementation, testing, deployment, and maintenance.",
  "Requirements phase identifies what to build. Output is often an SRS document and prioritized requirements list.",
  "Design phase defines architecture, database design, and component design. Output: design documents and diagrams.",
  "Implementation phase is coding based on design. Best practice: code reviews, version control, and clean coding standards.",
  "Testing phase validates that the system meets requirements and finds defects early to reduce cost of fixes.",
  "Deployment releases the software to users. It can be done using manual release, CI/CD pipelines, or phased rollout.",
  "Maintenance phase includes bug fixes, enhancements, performance improvements, and adapting to new environments.",
  "Common SDLC models: Waterfall, Spiral, Incremental, and Agile. Model selection depends on requirement stability and risk.",
  "SDLC benefits include better planning, cost estimation, quality assurance, documentation, and risk reduction.",
  "SDLC deliverables across phases include SRS, design docs, source code, test reports, and release notes."
 ],
 "Agile Model": [
  "Agile is an iterative and incremental approach where software is delivered in small working increments frequently.",
  "Agile values: individuals and interactions, working software, customer collaboration, responding to change.",
  "Agile reduces risk by delivering early and collecting feedback continuously.",
  "Agile uses a backlog that contains user stories and tasks prioritized by value.",
  "Sprint planning decides what work will be done during the sprint based on team capacity.",
  "Daily standup is a short meeting to track progress, blockers, and next steps.",
  "Sprint review demonstrates completed work to stakeholders and collects feedback.",
  "Sprint retrospective focuses on improving the team process for the next sprint.",
  "Agile metrics include velocity, burndown charts, lead time, and cycle time.",
  "Agile encourages continuous integration, automated testing, and incremental improvements."
 ],
 "Scrum": [
  "Scrum is an Agile framework that delivers work in time-boxed iterations called sprints (usually 1–4 weeks).",
  "Scrum roles: Product Owner (defines value), Scrum Master (facilitates), Developers (build increment).",
  "Artifacts: Product Backlog, Sprint Backlog, Increment. Each artifact increases transparency.",
  "Sprint Planning defines sprint goal and selects backlog items to deliver.",
  "Daily Scrum is a 15-minute event where the team synchronizes and plans the next 24 hours.",
  "Sprint Review inspects the increment and adapts the product backlog if needed.",
  "Sprint Retrospective inspects how the last sprint went and creates improvements.",
  "Definition of Done ensures consistent quality criteria for completed work.",
  "A user story describes a feature from user perspective with acceptance criteria.",
  "Scrum benefits: transparency, frequent delivery, adaptability, and continuous improvement."
 ],
 "UML": [
  "UML (Unified Modeling Language) is a standard visual language to model and document software systems.",
  "UML helps communicate system design using diagrams for structure and behavior.",
  "Structural diagrams include Class, Component, Deployment diagrams. They model system structure.",
  "Behavioral diagrams include Use Case, Sequence, Activity diagrams. They model system behavior.",
  "UML improves understanding between developers, analysts, and stakeholders.",
  "Class diagrams model classes, attributes, methods, and relationships.",
  "Sequence diagrams model message flow between objects over time.",
  "Use case diagrams show system functions and actors at high level.",
  "UML diagrams should be simple, consistent, and match requirements.",
  "UML can be used in both traditional and Agile development."
 ],
 "Use Case Diagram": [
  "A Use Case Diagram shows actors and use cases (system functions) to capture functional requirements.",
  "Actors represent users or external systems interacting with the system.",
  "Use cases represent goals or services provided by the system.",
  "Include relationship indicates one use case always uses another use case.",
  "Extend relationship indicates optional behavior based on a condition.",
  "Generalization shows inheritance between actors or use cases.",
  "Use case diagrams help define scope and identify system boundaries.",
  "They are useful during requirements gathering and analysis.",
  "Use case description includes preconditions, main flow, alternative flows, postconditions.",
  "Good use cases are goal-oriented and written from the user's perspective."
 ],
 "Class Diagram": [
  "A Class Diagram models classes with attributes and methods and their relationships.",
  "Association shows relationship between classes; multiplicity shows how many objects participate.",
  "Inheritance (generalization) models an 'is-a' relationship.",
  "Aggregation models a weak 'has-a' relationship; composition models strong ownership.",
  "Class diagrams guide object-oriented implementation and code structure.",
  "Visibility: + public, - private, # protected for attributes and methods.",
  "Interfaces define method signatures; classes implement interfaces.",
  "Class diagrams support maintainability by clarifying responsibilities.",
  "They help detect missing classes and relationships early.",
  "They are part of design documentation and architecture."
 ],
 "Sequence Diagram": [
  "A Sequence Diagram shows how objects interact through messages in time order.",
  "Lifelines represent objects; activation bars show when an object is executing.",
  "Messages can be synchronous (wait) or asynchronous (no wait).",
  "Return messages show values returned from function calls.",
  "Sequence diagrams help understand a scenario flow step-by-step.",
  "They are useful for designing APIs and method call order.",
  "They help detect missing interactions or incorrect sequence logic.",
  "Combined fragments (alt/opt/loop) model conditions and loops.",
  "They support debugging by visualizing runtime behavior.",
  "They are often derived from use cases."
 ],
 "Software Testing": [
  "Software testing is the process of evaluating software to find defects and verify requirements.",
  "Testing levels: unit, integration, system, acceptance testing.",
  "Functional testing checks features; non-functional testing checks performance, security, usability.",
  "Test cases include input data, steps, expected output, and actual output.",
  "Automated testing improves speed and reliability for regression tests.",
  "Regression testing ensures new changes do not break existing functionality.",
  "Test planning defines scope, strategy, tools, and schedule for testing.",
  "Defect life cycle includes: new, assigned, fixed, retest, closed.",
  "Good testing reduces risk and increases confidence before release.",
  "Code coverage measures how much code is executed by tests."
 ],
 "Unit Testing": [
  "Unit testing validates individual functions or classes in isolation.",
  "It is usually automated and runs frequently during development.",
  "Mocks and stubs isolate units from databases, APIs, or network dependencies.",
  "Unit testing supports safe refactoring and reduces debugging time.",
  "AAA pattern: Arrange, Act, Assert helps structure tests clearly.",
  "A good unit test is small, fast, deterministic, and independent.",
  "Edge cases should be tested such as null values, empty inputs, and boundaries.",
  "Coverage helps, but quality of tests is more important than 100% coverage.",
  "Popular frameworks: JUnit, NUnit, pytest, Jest (depending on language).",
  "Unit tests are part of CI pipelines for quick feedback."
 ],
 "Integration Testing": [
  "Integration testing verifies interactions between modules or services.",
  "It finds interface issues, incorrect data flow, and integration defects.",
  "Approaches: top-down, bottom-up, big-bang integration.",
  "API testing is often part of integration testing.",
  "Integration tests run after unit tests and before system tests.",
  "Test environment should match real integration points as much as possible.",
  "Mocking external services can help during early integration tests.",
  "Database integration tests verify queries, schema, and transactions.",
  "Integration testing supports microservices and distributed systems.",
  "CI can run integration tests on every merge to catch issues early."
 ],
 "System Testing": [
  "System testing evaluates the entire integrated system against requirements.",
  "It is end-to-end testing in an environment similar to production.",
  "System testing includes functional and non-functional checks.",
  "Performance testing measures response time, throughput, and resource usage.",
  "Security testing checks vulnerabilities and access control issues.",
  "Recovery testing checks how system behaves after failures.",
  "Compatibility testing checks behavior across browsers/devices/OS versions.",
  "System testing happens after integration testing.",
  "It validates that components work together as a full system.",
  "System testing results are used to decide readiness for release."
 ],
 "Version Control": [
  "Version control (Git) tracks changes and enables collaboration in software development.",
  "A commit saves a snapshot of changes with a message describing the update.",
  "Branches allow parallel development without breaking main code.",
  "Merge combines changes from different branches into one.",
  "Pull requests support code review before merging.",
  "Conflicts happen when changes overlap; they must be resolved manually.",
  "Branching strategies: Git Flow, trunk-based development.",
  "Best practices: small commits, meaningful messages, frequent pushes.",
  "Tags mark releases (v1.0, v2.0) for easy rollback.",
  "Version control supports CI/CD pipelines and safe deployments."
 ],
 "Software Maintenance": [
  "Software maintenance is work done after deployment to keep software useful and correct.",
  "Corrective maintenance fixes defects found after release.",
  "Adaptive maintenance updates software to work in new environments (OS, hardware, libraries).",
  "Perfective maintenance improves performance or adds enhancements.",
  "Preventive maintenance improves code quality to reduce future issues.",
  "Maintenance often costs more than development because system is already in production.",
  "Good documentation and automated tests reduce maintenance risk.",
  "Refactoring is improving internal code structure without changing behavior.",
  "Monitoring and logs help detect issues and support troubleshooting.",
  "A change request process ensures maintenance work is prioritized and tracked."
 ]
}

lessons = []
for topic in TOPICS:
    items = lesson_bank[topic]
    for i, text in enumerate(items, start=1):
        lessons.append({"topic": topic, "lesson_id": f"{topic}_{i}", "content": text})

df_lessons = pd.DataFrame(lessons)
df_lessons.to_csv("../backend/data/lessons.csv", index=False)

print("✅ Saved:", "../backend/data/lessons.csv", "Rows:", len(df_lessons))
df_lessons.head(3)

✅ Saved: ../backend/data/lessons.csv Rows: 130

  topic lesson_id                                            content
0  SDLC    SDLC_1  SDLC (Software Development Life Cycle) is a st...
1  SDLC    SDLC_2  Requirements phase identifies what to build. O...
2  SDLC    SDLC_3  Design phase defines architecture, database de...

In [3]:
resources = [
  {"topic":"SDLC","type":"Blog","title":"SDLC Overview (GeeksforGeeks)","url":"https://www.geeksforgeeks.org/software-development-life-cycle-sdlc/"},
  {"topic":"SDLC","type":"Video","title":"SDLC Explained (YouTube search)","url":"https://www.youtube.com/results?search_query=SDLC+explained"},
  {"topic":"Agile Model","type":"Blog","title":"Agile Overview (Atlassian)","url":"https://www.atlassian.com/agile"},
  {"topic":"Agile Model","type":"Video","title":"Agile Tutorial (YouTube search)","url":"https://www.youtube.com/results?search_query=agile+software+development+tutorial"},
  {"topic":"Scrum","type":"Docs","title":"The Scrum Guide (Official)","url":"https://scrumguides.org/"},
  {"topic":"Scrum","type":"Video","title":"Scrum Basics (YouTube search)","url":"https://www.youtube.com/results?search_query=scrum+basics"},
  {"topic":"UML","type":"Blog","title":"UML Guide (Visual Paradigm)","url":"https://www.visual-paradigm.com/guide/uml-unified-modeling-language/"},
  {"topic":"UML","type":"Video","title":"UML Tutorial (YouTube search)","url":"https://www.youtube.com/results?search_query=uml+tutorial"},
  {"topic":"Use Case Diagram","type":"Blog","title":"Use Case Diagram (Lucidchart)","url":"https://www.lucidchart.com/pages/uml-use-case-diagram"},
  {"topic":"Class Diagram","type":"Blog","title":"Class Diagram (Lucidchart)","url":"https://www.lucidchart.com/pages/uml-class-diagram"},
  {"topic":"Sequence Diagram","type":"Blog","title":"Sequence Diagram (Lucidchart)","url":"https://www.lucidchart.com/pages/uml-sequence-diagram"},
  {"topic":"Software Testing","type":"Blog","title":"Software Testing (Guru99)","url":"https://www.guru99.com/software-testing.html"},
  {"topic":"Unit Testing","type":"Blog","title":"Unit Testing (Martin Fowler)","url":"https://martinfowler.com/bliki/UnitTest.html"},
  {"topic":"Integration Testing","type":"Blog","title":"Integration Testing (Guru99)","url":"https://www.guru99.com/integration-testing.html"},
  {"topic":"System Testing","type":"Blog","title":"System Testing (Guru99)","url":"https://www.guru99.com/system-testing.html"},
  {"topic":"Version Control","type":"Docs","title":"Git Handbook (GitHub)","url":"https://guides.github.com/introduction/git-handbook/"},
  {"topic":"Version Control","type":"Video","title":"Git Tutorial (YouTube search)","url":"https://www.youtube.com/results?search_query=git+tutorial+for+beginners"},
  {"topic":"Software Maintenance","type":"Blog","title":"Software Maintenance (GeeksforGeeks)","url":"https://www.geeksforgeeks.org/software-maintenance/"}
]

df_res = pd.DataFrame(resources)
df_res.to_csv("../backend/data/resources.csv", index=False)

print("✅ Saved:", "../backend/data/resources.csv", "Rows:", len(df_res))
df_res.head(3)

✅ Saved: ../backend/data/resources.csv Rows: 18

,topic,type,title,url
0,SDLC,Blog,SDLC Overview (GeeksforGeeks),https://www.geeksforgeeks.org/software-develop...
1,SDLC,Video,SDLC Explained (YouTube search),https://www.youtube.com/results?search_query=S...
2,Agile Model,Blog,Agile Overview (Atlassian),https://www.atlassian.com/agile

In [4]:
questions = []
qid = 1

def add_mcq(topic, question, A, B, C, D, answer, difficulty=1):
    global qid
    questions.append({
        "id": qid,
        "topic": topic,
        "difficulty": difficulty,
        "question": question,
        "A": A, "B": B, "C": C, "D": D,
        "answer": answer
    })
    qid += 1

# ---- SDLC (15) ----
add_mcq("SDLC","SDLC stands for?","Software Development Life Cycle","System Design Life Cycle","Software Debug Life Cycle","None","A",1)
add_mcq("SDLC","Which phase comes after requirements?","Testing","Design","Deployment","Maintenance","B",1)
add_mcq("SDLC","Which document is created in requirements phase?","SRS","Source code","Test report","Release notes","A",2)
add_mcq("SDLC","Main purpose of SDLC is to?","Increase bugs","Provide structured development","Avoid documentation","Skip testing","B",2)
add_mcq("SDLC","Which is an SDLC model?","Waterfall","Bluetooth","Ethernet","DNS","A",1)
add_mcq("SDLC","Which phase focuses on writing code?","Design","Implementation","Maintenance","Deployment","B",1)
add_mcq("SDLC","Testing is mainly used to?","Add features","Find defects","Write SRS","Create UI","B",1)
add_mcq("SDLC","Maintenance phase occurs?","Before deployment","After deployment","Before design","Before requirements","B",1)
add_mcq("SDLC","Waterfall model is best when requirements are?","Changing daily","Stable","Unknown","Not needed","B",2)
add_mcq("SDLC","Which is a benefit of SDLC?","More confusion","Better quality control","No planning","No documentation","B",2)
add_mcq("SDLC","Which is NOT an SDLC phase?","Requirements","Design","Cooking","Testing","C",1)
add_mcq("SDLC","Deliverable of design phase is?","SRS","Design document","Test report","Bug list","B",2)
add_mcq("SDLC","Deployment means?","Writing code","Releasing to users","Fixing bugs","Drawing diagrams","B",1)
add_mcq("SDLC","Correct order is?","Design→Requirements","Requirements→Design","Testing→Requirements","Deployment→Design","B",2)
add_mcq("SDLC","SDLC helps mainly to reduce?","Quality","Risk","Documentation","Users","B",2)

# ---- Agile Model (15) ----
add_mcq("Agile Model","Agile development is mainly?","Iterative and incremental","Only documentation","Only testing","Only coding","A",1)
add_mcq("Agile Model","Agile focuses on?","Customer feedback","Fixed scope always","No changes","No meetings","A",1)
add_mcq("Agile Model","Agile delivers software in?","Big single release","Small increments","Only at end","Only yearly","B",1)
add_mcq("Agile Model","Agile welcomes?","No change","Change in requirements","No feedback","No testing","B",1)
add_mcq("Agile Model","Product Backlog contains?","Hardware list","User stories/tasks","Only code","Only bugs","B",1)
add_mcq("Agile Model","Sprint review happens?","Before sprint","After sprint","Only yearly","Never","B",1)
add_mcq("Agile Model","Daily standup is for?","Long speeches","Sync progress/blockers","Hiring","Deploying","B",1)
add_mcq("Agile Model","Agile reduces risk by?","Late delivery","Frequent delivery","No testing","No planning","B",2)
add_mcq("Agile Model","Agile metric is?","Velocity","Voltage","Viscosity","Volume","A",2)
add_mcq("Agile Model","Agile values working software over?","Documentation","Testing","Coding","Design","A",2)
add_mcq("Agile Model","In Agile, requirements are?","Fixed forever","Evolving","Not needed","Always unknown","B",1)
add_mcq("Agile Model","Retrospective is used to?","Blame people","Improve process","Stop project","Write SRS","B",2)
add_mcq("Agile Model","Increment means?","Working product part","Only design","Only test plan","Only backlog","A",2)
add_mcq("Agile Model","Agile encourages?","Continuous integration","No integration","No teamwork","No feedback","A",2)
add_mcq("Agile Model","Agile is best for?","High change projects","No change projects","No users","No deadlines","A",2)

# ---- Scrum (15) ----
add_mcq("Scrum","Scrum roles include?","Product Owner","Database Admin only","Network Admin only","None","A",1)
add_mcq("Scrum","A sprint is usually?","1–4 weeks","1 year","1 day always","6 months","A",1)
add_mcq("Scrum","Daily Scrum is also called?","Daily standup","Design meeting","Deployment meeting","Retirement","A",1)
add_mcq("Scrum","Scrum Master mainly?","Writes code only","Facilitates Scrum","Approves salary","Designs DB","B",2)
add_mcq("Scrum","Product Owner is responsible for?","Backlog priority","Server setup","UI colors","Testing only","A",2)
add_mcq("Scrum","Sprint Planning decides?","Sprint goal & work","Company finance","Hardware purchase","Marketing plan","A",2)
add_mcq("Scrum","Sprint Review is for?","Demo and feedback","Punishment","Hiring","Database tuning","A",2)
add_mcq("Scrum","Sprint Retrospective is for?","Process improvement","Release to users","Write code","Install OS","A",2)
add_mcq("Scrum","Definition of Done ensures?","Quality criteria","More meetings","No tests","No docs","A",2)
add_mcq("Scrum","Sprint Backlog contains?","Selected sprint items","Company rules","User passwords","Contracts","A",2)
add_mcq("Scrum","Increment means?","Potentially shippable work","Only documentation","Only testing","Only planning","A",2)
add_mcq("Scrum","Scrum is part of?","Agile","Waterfall","Spiral only","None","A",1)
add_mcq("Scrum","Scrum artifacts include?","Product Backlog","CPU","RAM","Router","A",1)
add_mcq("Scrum","Scrum promotes?","Transparency","Hidden work","No feedback","No planning","A",2)
add_mcq("Scrum","Sprint goal is?","Objective of sprint","Database name","Team salary","Server IP","A",2)

# ---- UML (15) ----
add_mcq("UML","UML stands for?","Unified Modeling Language","Universal Machine Language","User Modeling Language","None","A",1)
add_mcq("UML","UML is mainly used to?","Model software","Run servers","Encrypt data","Sell products","A",1)
add_mcq("UML","Which is UML diagram?","Class Diagram","ER only","FFT","CPU Diagram","A",1)
add_mcq("UML","Class diagram is?","Structural","Behavioral","Network","Hardware","A",2)
add_mcq("UML","Sequence diagram is?","Behavioral","Structural","Database","UI only","A",2)
add_mcq("UML","Use case diagram shows?","Actors & use cases","Tables","Binary trees","Servers","A",1)
add_mcq("UML","UML helps?","Communication","More bugs","Less clarity","No design","A",2)
add_mcq("UML","UML is used during?","Design/analysis","Only deployment","Only maintenance","Only coding","A",1)
add_mcq("UML","Behavioral diagrams show?","Interactions","Class attributes","DB schema","RAM usage","A",2)
add_mcq("UML","Structural diagrams show?","Static structure","Time order","Network traffic","CPU speed","A",2)
add_mcq("UML","UML can document?","Software systems","Weather","Sports","Music","A",1)
add_mcq("UML","UML supports?","Different views","Only one view","No views","Only code","A",2)
add_mcq("UML","UML improves?","Design clarity","Confusion","Randomness","Latency only","A",2)
add_mcq("UML","UML is helpful for?","OOP design","Cooking","Driving","Painting","A",1)
add_mcq("UML","UML diagrams are best when?","Simple and consistent","Very complex always","No labels","No actors","A",2)

# ---- Use Case Diagram (15) ----
add_mcq("Use Case Diagram","Use case diagrams capture?","Functional requirements","DB schema","CPU speed","Network topology","A",1)
add_mcq("Use Case Diagram","Actors represent?","External roles/systems","Database tables","Classes","Functions","A",1)
add_mcq("Use Case Diagram","Use cases represent?","User goals","RAM usage","Server ports","Files","A",1)
add_mcq("Use Case Diagram","System boundary shows?","Scope of system","Code style","Team size","Server location","A",2)
add_mcq("Use Case Diagram","Include relationship means?","Always uses","Optional","Inheritance","No relation","A",2)
add_mcq("Use Case Diagram","Extend relationship means?","Optional behavior","Always uses","Database link","UI theme","A",2)
add_mcq("Use Case Diagram","Use case diagram is mostly?","High-level view","Low-level code","Database code","Hardware spec","A",1)
add_mcq("Use Case Diagram","Generalization shows?","Inheritance","Testing","Deployment","Backup","A",2)
add_mcq("Use Case Diagram","Use cases should be?","Goal-oriented","Random","Hardware-based","Private always","A",2)
add_mcq("Use Case Diagram","Actor can be?","Human or system","Only human","Only DB","Only server","A",2)
add_mcq("Use Case Diagram","Use case diagrams help to?","Define scope","Write code","Deploy app","Fix bugs","A",1)
add_mcq("Use Case Diagram","Use case diagram includes?","Actors","IP address","CPU","RAM","A",1)
add_mcq("Use Case Diagram","Use case description includes?","Main flow","RAM size","CPU speed","Server ports","A",2)
add_mcq("Use Case Diagram","Use cases are named with?","Verb phrases","Numbers only","Random letters","Hardware names","A",2)
add_mcq("Use Case Diagram","Use case diagram is created in?","Requirements/analysis","Only testing","Only deployment","Only maintenance","A",1)

# ---- Class Diagram (15) ----
add_mcq("Class Diagram","Class diagram models?","Classes/relationships","Network","CPU","Web hosting","A",1)
add_mcq("Class Diagram","Inheritance means?","Is-a","Has-a weak","Owns strongly","No relation","A",2)
add_mcq("Class Diagram","Composition is?","Strong ownership","Weak ownership","No ownership","Only UI","A",2)
add_mcq("Class Diagram","Aggregation is?","Weak has-a","Strong has-a","Is-a","None","A",2)
add_mcq("Class Diagram","Multiplicity shows?","How many objects","Code speed","DB size","CPU usage","A",2)
add_mcq("Class Diagram","Visibility '+' means?","Public","Private","Protected","Package","A",2)
add_mcq("Class Diagram","Visibility '-' means?","Private","Public","Protected","None","A",2)
add_mcq("Class Diagram","Association means?","Relationship","Compilation","Deployment","Testing","A",1)
add_mcq("Class Diagram","Class diagram is?","Structural","Behavioral","Network","Hardware","A",1)
add_mcq("Class Diagram","Attributes belong to?","Class","Actor","Server","Database only","A",1)
add_mcq("Class Diagram","Methods represent?","Operations","Tables","Ports","Files","A",1)
add_mcq("Class Diagram","Interface defines?","Method signatures","CPU usage","RAM size","Network speed","A",2)
add_mcq("Class Diagram","Class diagrams help?","OOP design","Cooking","Music","Sports","A",1)
add_mcq("Class Diagram","Class diagram relationship 'is-a' is?","Generalization","Aggregation","Composition","Include","A",2)
add_mcq("Class Diagram","Class diagram used in?","Design phase","Only testing","Only deployment","Only maintenance","A",1)

# ---- Sequence Diagram (15) ----
add_mcq("Sequence Diagram","Sequence diagram shows?","Message order","Class attributes","DB tables","CPU speed","A",1)
add_mcq("Sequence Diagram","Lifeline represents?","Object","Database table","Router","CPU","A",1)
add_mcq("Sequence Diagram","Activation bar shows?","Execution","Storage","Network","Cooling","A",2)
add_mcq("Sequence Diagram","Synchronous message means?","Waits for response","Never waits","Deletes DB","Changes UI","A",2)
add_mcq("Sequence Diagram","Asynchronous message means?","Does not wait","Always waits","Writes SRS","Deploys app","A",2)
add_mcq("Sequence Diagram","Sequence diagrams are?","Behavioral","Structural","Hardware","Network","A",1)
add_mcq("Sequence Diagram","Return message shows?","Returned value","CPU usage","RAM usage","Disk usage","A",2)
add_mcq("Sequence Diagram","alt fragment is used for?","Conditions","Deployment","Compilation","Backup","A",2)
add_mcq("Sequence Diagram","loop fragment is used for?","Repeats","Deletes","Deploys","Encrypts","A",2)
add_mcq("Sequence Diagram","Sequence diagrams help?","Understand flow","Change RAM","Fix router","Buy server","A",1)
add_mcq("Sequence Diagram","Messages go between?","Objects","Countries","Routers only","CPU only","A",1)
add_mcq("Sequence Diagram","Sequence diagrams derive from?","Use cases","Git commits","DNS","SMTP","A",2)
add_mcq("Sequence Diagram","Order in sequence diagram is from?","Top to bottom","Bottom to top","Left to right only","Random","A",1)
add_mcq("Sequence Diagram","Sequence diagrams are useful for?","Scenario design","Hardware upgrades","Billing","Marketing","A",2)
add_mcq("Sequence Diagram","Sequence diagram shows time?","Yes","No","Only sometimes","Never","A",1)

# ---- Testing topics (Software/Unit/Integration/System) (15 each but smaller base) ----
# Software Testing (15)
add_mcq("Software Testing","Purpose of testing is?","Find defects","Create defects","Avoid users","Stop development","A",1)
add_mcq("Software Testing","Regression testing ensures?","No old features break","More bugs","No documentation","No deployment","A",2)
add_mcq("Software Testing","Functional testing checks?","Features","CPU speed only","RAM only","Cables","A",1)
add_mcq("Software Testing","Non-functional testing includes?","Performance","Only UI color","Only syntax","Only comments","A",2)
add_mcq("Software Testing","Test case contains?","Steps and expected result","Only code","Only design","Only hardware","A",1)
add_mcq("Software Testing","Unit testing is done on?","Small units","Whole system","Only UI","Only DB","A",1)
add_mcq("Software Testing","Integration testing checks?","Module interaction","Single line code","Only UI","Only docs","A",1)
add_mcq("Software Testing","System testing checks?","Whole system","Only unit","Only integration","Only SRS","A",1)
add_mcq("Software Testing","Acceptance testing is done by?","Customer/end user","Only developer","Only DB admin","Only server admin","A",2)
add_mcq("Software Testing","Bug/defect means?","Error in software","New feature","UI theme","Version control","A",1)
add_mcq("Software Testing","Smoke testing is?","Basic build verification","Deep security testing","Network setup","DB backup","A",2)
add_mcq("Software Testing","Sanity testing is?","Narrow regression","Hardware test","OS install","UI design","A",2)
add_mcq("Software Testing","Test plan defines?","Strategy/scope","CPU model","RAM size","Git branch","A",2)
add_mcq("Software Testing","Automation is useful for?","Regression tests","Cooking","Driving","Painting","A",2)
add_mcq("Software Testing","Coverage measures?","Code exercised","Team size","Server count","User count","A",2)

# Unit Testing (15)
add_mcq("Unit Testing","Unit tests focus on?","Functions/classes","Whole system","Deployment","Network","A",1)
add_mcq("Unit Testing","Mocks are used to?","Isolate dependencies","Increase latency","Deploy code","Write UML","A",2)
add_mcq("Unit Testing","AAA stands for?","Arrange Act Assert","Add Assign Apply","Ask Answer Act","None","A",2)
add_mcq("Unit Testing","Unit tests should be?","Fast and independent","Slow always","Manual only","Random","A",2)
add_mcq("Unit Testing","Unit tests run often in?","CI pipeline","Marketing","Billing","Recruiting","A",1)
add_mcq("Unit Testing","Edge case means?","Boundary input","Database table","Server IP","UI theme","A",2)
add_mcq("Unit Testing","Refactoring is safer with?","Unit tests","No tests","No code","No docs","A",2)
add_mcq("Unit Testing","A good unit test is?","Deterministic","Random","Network dependent","Slow","A",2)
add_mcq("Unit Testing","Stubs are used to?","Provide fake response","Increase bug","Deploy system","Draw diagram","A",2)
add_mcq("Unit Testing","Coverage 100% means?","All code executed","No bugs","Perfect app","No maintenance","A",2)
add_mcq("Unit Testing","Unit testing reduces?","Debugging time","Quality","Teamwork","Documentation","A",2)
add_mcq("Unit Testing","Unit tests should avoid?","External services","Functions","Classes","Assertions","A",2)
add_mcq("Unit Testing","Unit test checks?","Expected output","Marketing","Finance","Hardware","A",1)
add_mcq("Unit Testing","TDD means?","Test-driven development","Top-down design","Time driven dev","None","A",2)
add_mcq("Unit Testing","Unit tests are written by?","Developers","Only customers","Only Scrum Master","Only PO","A",1)

# Integration Testing (15)
add_mcq("Integration Testing","Integration testing focuses on?","Module interaction","Single method","Only UI","Only docs","A",1)
add_mcq("Integration Testing","Big-bang integration means?","Integrate all at once","One by one always","Only top-down","Only bottom-up","A",2)
add_mcq("Integration Testing","Top-down integration starts from?","Top modules","Bottom modules","Database","UI only","A",2)
add_mcq("Integration Testing","Bottom-up integration starts from?","Low-level modules","High-level modules","UI only","Docs only","A",2)
add_mcq("Integration Testing","Integration tests detect?","Interface defects","Spelling mistakes only","CPU overheating","Power failure","A",1)
add_mcq("Integration Testing","API tests are part of?","Integration testing","Unit testing only","Deployment only","Maintenance only","A",2)
add_mcq("Integration Testing","Integration tests run after?","Unit tests","System tests","Deployment","Maintenance","A",1)
add_mcq("Integration Testing","Integration environment should be?","Similar to real","Completely random","No DB","No services","A",2)
add_mcq("Integration Testing","Mocking external service helps when?","Service unavailable","Always required","Never allowed","Only in UML","A",2)
add_mcq("Integration Testing","Database integration tests verify?","Queries/transactions","UI colors","Sprint goals","Use cases","A",2)
add_mcq("Integration Testing","Integration testing is important for?","Microservices","Cooking","Music","Sports","A",2)
add_mcq("Integration Testing","Integration bugs occur due to?","Wrong interfaces","Perfect code","No changes","No testing","A",2)
add_mcq("Integration Testing","Contract testing checks?","API compatibility","CPU speed","RAM usage","Hard disk","A",2)
add_mcq("Integration Testing","Integration testing reduces?","System-level failures","Documentation","Velocity","Meeting time","A",2)
add_mcq("Integration Testing","Integration test uses?","Multiple modules","Single function","Only comments","Only docs","A",1)

# System Testing (15)
add_mcq("System Testing","System testing tests?","Complete system","Single function","Only DB","Only UI","A",1)
add_mcq("System Testing","System testing occurs after?","Integration testing","Deployment","Maintenance","Coding","A",1)
add_mcq("System Testing","End-to-end testing is part of?","System testing","Unit testing","Only docs","Only UML","A",1)
add_mcq("System Testing","Performance testing measures?","Speed/throughput","Color theme","Variable names","Commits","A",2)
add_mcq("System Testing","Security testing checks?","Vulnerabilities","Fonts","Spacing","Comments","A",2)
add_mcq("System Testing","Recovery testing checks?","System after failure","UI design","Sprint planning","Git branches","A",2)
add_mcq("System Testing","Compatibility testing checks?","Different devices/browsers","Only DB","Only API","Only code","A",2)
add_mcq("System Testing","System testing environment should be?","Production-like","Random","No DB","No services","A",2)
add_mcq("System Testing","System testing verifies?","Requirements","Only syntax","Only comments","Only UML","A",1)
add_mcq("System Testing","Load testing checks?","Behavior under load","Cooking speed","Music volume","Screen size","A",2)
add_mcq("System Testing","Stress testing checks?","Limits beyond capacity","UI only","DB only","Docs only","A",2)
add_mcq("System Testing","Acceptance criteria relates to?","Requirements validation","Git commits","CPU speed","RAM size","A",2)
add_mcq("System Testing","System testing finds?","Integration issues + behavior","Only typos","Only design mistakes","Only branch issues","A",2)
add_mcq("System Testing","System testing is mostly?","Black-box","Compiler","Assembler","Linker","A",2)
add_mcq("System Testing","Release decision depends on?","System test results","Only UML","Only Git","Only meetings","A",2)

# ---- Version Control (15) ----
add_mcq("Version Control","Git is used for?","Version control","Video editing","Database storage","Emailing","A",1)
add_mcq("Version Control","Commit is?","Snapshot of changes","Server backup","UI theme","Database table","A",1)
add_mcq("Version Control","Branch is used for?","Parallel work","Only testing","Only deployment","Only docs","A",1)
add_mcq("Version Control","Merge means?","Combine branches","Delete code","Write UML","Run tests","A",1)
add_mcq("Version Control","Pull request is used for?","Code review","Cooking","Music","Sports","A",1)
add_mcq("Version Control","Conflict happens when?","Overlapping changes","No changes","Perfect merges","No branches","A",2)
add_mcq("Version Control","Rollback means?","Go to previous version","Increase bugs","Deploy faster","No tests","A",2)
add_mcq("Version Control","Tag is used for?","Mark release","Write tests","Create UML","Install OS","A",2)
add_mcq("Version Control","Trunk-based development means?","Small branches, frequent merge","No merges","No branches","No commits","A",2)
add_mcq("Version Control","Git remote is?","Repo on server","UI component","Database index","CPU core","A",2)
add_mcq("Version Control","Clone means?","Copy repo locally","Delete repo","Merge branches","Create issue","A",1)
add_mcq("Version Control","Push means?","Upload commits","Download commits","Run tests","Create diagram","A",1)
add_mcq("Version Control","Pull means?","Download updates","Upload updates","Delete branch","Run UML","A",1)
add_mcq("Version Control","Staging area is?","Before commit area","After deployment","Testing environment","Production","A",2)
add_mcq("Version Control","Best practice commit message is?","Meaningful","Random","Empty","Only numbers","A",2)

# ---- Software Maintenance (15) ----
add_mcq("Software Maintenance","Maintenance happens?","After deployment","Before requirements","Before coding","Before design","A",1)
add_mcq("Software Maintenance","Corrective maintenance is?","Bug fixing","New OS install","UI redesign","Prevent future issues","A",2)
add_mcq("Software Maintenance","Adaptive maintenance is?","Adapt to new environment","Fix bugs only","Write UML","Merge code","A",2)
add_mcq("Software Maintenance","Perfective maintenance is?","Enhancements/performance","Only bug fixes","Only deployment","Only testing","A",2)
add_mcq("Software Maintenance","Preventive maintenance is?","Improve maintainability","Delete code","Stop tests","No changes","A",2)
add_mcq("Software Maintenance","Refactoring is?","Improve code structure","Add new feature","Deploy app","Write SRS","A",2)
add_mcq("Software Maintenance","Monitoring helps?","Detect issues","Increase bugs","Skip testing","No docs","A",2)
add_mcq("Software Maintenance","Logs are used to?","Debug and audit","Change UI","Write UML","Merge branches","A",2)
add_mcq("Software Maintenance","Patch release is?","Small fix update","Hardware upgrade","New laptop","New office","A",1)
add_mcq("Software Maintenance","Maintenance cost is reduced by?","Good tests/docs","No tests","No docs","No code reviews","A",2)
add_mcq("Software Maintenance","Change request is?","Request to modify system","CPU request","RAM request","DNS request","A",2)
add_mcq("Software Maintenance","Corrective maintenance addresses?","Defects","New features only","New OS only","New market","A",2)
add_mcq("Software Maintenance","Adaptive maintenance example?","Support new OS","Fix typo","Add button","Rename variable","A",2)
add_mcq("Software Maintenance","Perfective maintenance example?","Improve performance","Fix crash","Support new OS","Prevent issues","A",2)
add_mcq("Software Maintenance","Preventive maintenance example?","Refactor + add tests","Add feature","Deploy app","Remove docs","A",2)

# Save
df_q = pd.DataFrame(questions)
df_q.to_csv("../backend/data/questions.csv", index=False)

print("✅ Saved:", "../backend/data/questions.csv", "Rows:", len(df_q))
df_q.head(3)

✅ Saved: ../backend/data/questions.csv Rows: 195

,id,topic,difficulty,question,A,B,C,D,answer
0,1,SDLC,1,SDLC stands for?,Software Development Life Cycle,System Design Life Cycle,Software Debug Life Cycle,None,A
1,2,SDLC,1,Which phase comes after requirements?,Testing,Design,Deployment,Maintenance,B
2,3,SDLC,2,Which document is created in requirements phase?,SRS,Source code,Test report,Release notes,A

In [5]:
import pandas as pd
from pathlib import Path
import random

random.seed(42)

TOPICS = [
  "SDLC",
  "Agile Model",
  "Scrum",
  "UML",
  "Use Case Diagram",
  "Class Diagram",
  "Sequence Diagram",
  "Software Testing",
  "Unit Testing",
  "Integration Testing",
  "System Testing",
  "Version Control",
  "Software Maintenance"
]

# ---- Base facts per topic (used to auto-create variants) ----
FACTS = {
 "SDLC": {
   "defs": ["Software Development Life Cycle", "requirements, design, implementation, testing, deployment, maintenance"],
   "keywords": ["requirements", "design", "implementation", "testing", "deployment", "maintenance"],
   "models": ["Waterfall", "Spiral", "Incremental", "Agile"]
 },
 "Agile Model": {
   "defs": ["iterative and incremental", "frequent delivery", "responding to change"],
   "keywords": ["backlog", "sprint", "standup", "review", "retrospective", "increment"],
   "models": ["Scrum", "Kanban", "XP"]
 },
 "Scrum": {
   "defs": ["framework with sprints", "roles: Product Owner, Scrum Master, Developers"],
   "keywords": ["Product Backlog", "Sprint Backlog", "Increment", "Sprint Planning", "Daily Scrum", "Review", "Retrospective"],
   "models": ["Sprint", "Backlog", "DoD"]
 },
 "UML": {
   "defs": ["Unified Modeling Language", "standard modeling language"],
   "keywords": ["structural", "behavioral", "diagrams", "model"],
   "models": ["Class", "Sequence", "Use Case", "Activity"]
 },
 "Use Case Diagram": {
   "defs": ["actors and use cases", "functional requirements"],
   "keywords": ["actor", "use case", "include", "extend", "system boundary"],
   "models": ["include", "extend", "generalization"]
 },
 "Class Diagram": {
   "defs": ["classes and relationships", "attributes and methods"],
   "keywords": ["association", "inheritance", "aggregation", "composition", "multiplicity"],
   "models": ["association", "generalization", "composition"]
 },
 "Sequence Diagram": {
   "defs": ["message flow over time", "object interactions"],
   "keywords": ["lifeline", "activation", "message", "alt", "loop", "return"],
   "models": ["sync", "async", "return"]
 },
 "Software Testing": {
   "defs": ["find defects", "verify requirements"],
   "keywords": ["functional", "non-functional", "regression", "test case", "defect"],
   "models": ["unit", "integration", "system", "acceptance"]
 },
 "Unit Testing": {
   "defs": ["tests smallest units", "fast and isolated"],
   "keywords": ["mock", "stub", "AAA", "TDD", "coverage"],
   "models": ["Arrange-Act-Assert", "TDD"]
 },
 "Integration Testing": {
   "defs": ["tests module interactions", "interface defects"],
   "keywords": ["top-down", "bottom-up", "big-bang", "API", "contract"],
   "models": ["top-down", "bottom-up", "big-bang"]
 },
 "System Testing": {
   "defs": ["tests whole system", "end-to-end"],
   "keywords": ["performance", "security", "compatibility", "recovery", "load"],
   "models": ["end-to-end", "UAT"]
 },
 "Version Control": {
   "defs": ["track changes", "collaboration with Git"],
   "keywords": ["commit", "branch", "merge", "pull request", "conflict", "tag"],
   "models": ["Git Flow", "trunk-based"]
 },
 "Software Maintenance": {
   "defs": ["post-deployment work", "fixes and enhancements"],
   "keywords": ["corrective", "adaptive", "perfective", "preventive", "refactoring", "monitoring"],
   "models": ["corrective", "adaptive", "perfective", "preventive"]
 }
}

def make_options(correct, wrongs):
    # ensure 3 wrong options + 1 correct
    options = wrongs[:3] + [correct]
    random.shuffle(options)
    letters = ["A","B","C","D"]
    mapping = dict(zip(letters, options))
    answer = [k for k,v in mapping.items() if v == correct][0]
    return mapping, answer

def gen_question(topic, i):
    f = FACTS[topic]
    diff = random.choice([1,1,2,2,3])  # more easy/medium

    # patterns
    patterns = [
      ("definition", lambda: (f"What best describes {topic}?", f["defs"][0])),
      ("keyword",    lambda: (f"Which term is most related to {topic}?", random.choice(f["keywords"]))),
      ("true_purpose",lambda: (f"The main purpose of {topic} is to:", random.choice(f["defs"]))),
      ("not_related", lambda: (f"Which is NOT related to {topic}?", "Not related")),
      ("concept",    lambda: (f"Which concept belongs to {topic}?", random.choice(f["models"]))),
    ]

    p, builder = random.choice(patterns)
    qtext, correct = builder()

    # wrong pool (generic wrong answers)
    wrong_pool = [
      "Bluetooth protocol", "CPU scheduling", "Database normalization only", "Network routing",
      "Cooking recipe", "Hardware installation", "Email SMTP", "DNS resolution",
      "Random guessing", "User interface theme"
    ]

    # add topic-specific wrongs
    topic_wrongs = []
    for t2 in TOPICS:
      if t2 != topic:
        topic_wrongs.append(t2)

    wrongs = wrong_pool + topic_wrongs
    random.shuffle(wrongs)

    if p == "not_related":
      # for NOT related, correct is "Not related"; make other 3 be related keywords/models
      related = list(set(f["keywords"] + f["models"]))
      random.shuffle(related)
      mapping, answer = make_options("Not related", related + wrongs)
      return qtext, mapping, answer, diff

    mapping, answer = make_options(correct, wrongs)
    return qtext, mapping, answer, diff

# ---- Build ~520 questions (40 per topic) ----
rows = []
qid = 1
PER_TOPIC = 40  # 40 * 13 = 520

for topic in TOPICS:
    for i in range(PER_TOPIC):
        qtext, mapping, ans, diff = gen_question(topic, i)
        rows.append({
            "id": qid,
            "topic": topic,
            "difficulty": diff,
            "question": qtext,
            "A": mapping["A"],
            "B": mapping["B"],
            "C": mapping["C"],
            "D": mapping["D"],
            "answer": ans
        })
        qid += 1

df_q = pd.DataFrame(rows)
Path("../backend/data").mkdir(parents=True, exist_ok=True)
df_q.to_csv("../backend/data/questions.csv", index=False)

print("✅ Saved ../backend/data/questions.csv")
print("Total questions:", len(df_q))
df_q.sample(5)

✅ Saved ../backend/data/questions.csv
Total questions: 520

,id,topic,difficulty,question,A,B,C,D,answer
187,188,Use Case Diagram,2,Which concept belongs to Use Case Diagram?,User interface theme,UML,include,DNS resolution,C
490,491,Software Maintenance,1,Which term is most related to Software Mainten...,DNS resolution,Unit Testing,preventive,User interface theme,C
159,160,UML,3,Which term is most related to UML?,DNS resolution,Bluetooth protocol,behavioral,Database normalization only,C
156,157,UML,2,Which is NOT related to UML?,diagrams,Activity,Not related,structural,C
216,217,Class Diagram,3,Which concept belongs to Class Diagram?,generalization,Sequence Diagram,Email SMTP,SDLC,A

In [6]:
import pandas as pd
from pathlib import Path
import random

random.seed(42)

topics = [
  "SDLC","Agile","Scrum","UML","Use case diagram","Class diagram","Sequence diagram",
  "software testing","unit testing","integration testing","system testing",
  "Git","version control","software maintenance"
]

greeting = [
 "hi", "hello", "hey", "good morning", "good evening", "hi tutor", "hello bot", "hey there"
]

explain = []
for t in topics:
    explain += [
      f"explain {t}",
      f"what is {t}?",
      f"give me notes on {t}",
      f"teach me {t}",
      f"define {t}",
      f"can you explain {t} with example?",
      f"explain {t} in simple words"
    ]

quiz = []
for t in topics:
    quiz += [
      f"quiz me on {t}",
      f"start a quiz on {t}",
      f"give mcq on {t}",
      f"ask questions about {t}",
      f"i want a quiz for {t}"
    ]

check_answer = []
for t in topics:
    check_answer += [
      f"check my answer on {t}",
      f"is my answer correct for {t}?",
      f"i chose option A, is it correct?",
      f"my answer is B, correct?",
      f"explain why option C is wrong"
    ]

recommend = []
for t in topics:
    recommend += [
      f"recommend resources for {t}",
      f"give me youtube links for {t}",
      f"best website to learn {t}",
      f"recommend tutorials on {t}",
      f"suggest materials for {t}"
    ]

other = [
 "tell me a joke", "what is your name", "open google", "who is the president", "play music",
 "can you do my assignment", "give me movie recommendations"
]

data = []
def add(intent, texts):
    for x in texts:
        data.append({"text": x, "intent": intent})

add("greeting", greeting)
add("explain", explain)
add("quiz", quiz)
add("check_answer", check_answer)
add("recommend", recommend)
add("other", other)

df_intent = pd.DataFrame(data).sample(frac=1, random_state=42).reset_index(drop=True)

Path("../data").mkdir(parents=True, exist_ok=True)
df_intent.to_csv("../data/intent_dataset.csv", index=False)

print("✅ Saved ../data/intent_dataset.csv")
print("Rows:", len(df_intent))
df_intent.head(10)

✅ Saved ../data/intent_dataset.csv
Rows: 323

                                                text        intent
0                   give mcq on software maintenance          quiz
1                      start a quiz on Class diagram          quiz
2         is my answer correct for Use case diagram?  check_answer
3                                      what is SDLC?       explain
4  can you explain software maintenance with exam...       explain
5                          ask questions about Scrum          quiz
6                      recommend resources for Scrum     recommend
7                         give mcq on system testing          quiz
8                  check my answer on system testing  check_answer
9     give me youtube links for software maintenance     recommend

In [7]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
import joblib

# Paths
intent_path = Path("../data/intent_dataset.csv")
Path("../backend/models").mkdir(parents=True, exist_ok=True)

# Load
df = pd.read_csv(intent_path)
df = df.dropna()

# Split
X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["intent"],
    test_size=0.2, random_state=42, stratify=df["intent"]
)

# Train model
intent_model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=1)),
    ("clf", LinearSVC())
])

intent_model.fit(X_train, y_train)
pred = intent_model.predict(X_test)

print("=== INTENT MODEL REPORT ===")
print(classification_report(y_test, pred, zero_division=0))

# Save joblib
joblib.dump(intent_model, "../backend/models/intent_model.joblib")
print("✅ Saved: ../backend/models/intent_model.joblib")

=== INTENT MODEL REPORT ===
              precision    recall  f1-score   support

check_answer       1.00      1.00      1.00        14
     explain       0.87      1.00      0.93        20
    greeting       0.00      0.00      0.00         2
       other       0.00      0.00      0.00         1
        quiz       1.00      1.00      1.00        14
   recommend       1.00      1.00      1.00        14

    accuracy                           0.95        65
   macro avg       0.64      0.67      0.66        65
weighted avg       0.91      0.95      0.93        65

✅ Saved: ../backend/models/intent_model.joblib

In [8]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
import joblib

topic_path = Path("../data/topic_dataset.csv")
Path("../backend/models").mkdir(parents=True, exist_ok=True)

df = pd.read_csv(topic_path)
df = df.dropna()

X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["topic"],
    test_size=0.2, random_state=42, stratify=df["topic"]
)

topic_model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=1)),
    ("clf", LinearSVC())
])

topic_model.fit(X_train, y_train)
pred = topic_model.predict(X_test)

print("=== TOPIC MODEL REPORT ===")
print(classification_report(y_test, pred, zero_division=0))

joblib.dump(topic_model, "../backend/models/topic_model.joblib")
print("✅ Saved: ../backend/models/topic_model.joblib")

=== TOPIC MODEL REPORT ===
                      precision    recall  f1-score   support

         Agile Model       1.00      1.00      1.00         2
       Class Diagram       1.00      1.00      1.00         2
 Integration Testing       1.00      1.00      1.00         2
                SDLC       1.00      1.00      1.00         2
               Scrum       1.00      1.00      1.00         2
    Sequence Diagram       1.00      1.00      1.00         2
Software Maintenance       1.00      1.00      1.00         2
    Software Testing       1.00      1.00      1.00         2
      System Testing       1.00      1.00      1.00         2
                 UML       1.00      1.00      1.00         2
        Unit Testing       1.00      1.00      1.00         2
    Use Case Diagram       1.00      1.00      1.00         2
     Version Control       1.00      1.00      1.00         2

            accuracy                           1.00        26
           macro avg       1.00      1.00      1.00        26
        weighted avg       1.00      1.00      1.00        26

✅ Saved: ../backend/models/topic_model.joblib

In [9]:
import json
import joblib
from pathlib import Path

Path("../backend/models").mkdir(parents=True, exist_ok=True)

def export_linear_svc_pipeline(joblib_path, out_json_path):
    pipe = joblib.load(joblib_path)
    tfidf = pipe.named_steps["tfidf"]
    clf = pipe.named_steps["clf"]

    payload = {
        "ngram_range": list(tfidf.ngram_range),
        "lowercase": tfidf.lowercase,
        "vocabulary_": tfidf.vocabulary_,
        "idf_": tfidf.idf_.tolist(),
        "classes_": clf.classes_.tolist(),
        "coef_": clf.coef_.tolist(),
        "intercept_": clf.intercept_.tolist()
    }

    with open(out_json_path, "w", encoding="utf-8") as f:
        json.dump(payload, f)

export_linear_svc_pipeline("../backend/models/intent_model.joblib", "../backend/models/intentModel.json")
export_linear_svc_pipeline("../backend/models/topic_model.joblib", "../backend/models/topicModel.json")

print("✅ Exported:")
print(" - ../backend/models/intentModel.json")
print(" - ../backend/models/topicModel.json")

✅ Exported:
 - ../backend/models/intentModel.json
 - ../backend/models/topicModel.json

In [10]:
import pandas as pd

df = pd.read_csv("../data/intent_dataset.csv")

# add more greeting examples
more_greetings = [
 "hi",
 "hello",
 "hey",
 "good morning",
 "good afternoon",
 "good evening",
 "hi there",
 "hello tutor",
 "hey bot",
 "hello assistant",
 "hi ai tutor",
 "greetings",
 "how are you",
 "hey tutor",
 "hi teacher"
]

# add more other examples
more_other = [
 "tell me a joke",
 "what is your name",
 "who created you",
 "what can you do",
 "are you human",
 "open youtube",
 "open google",
 "play music",
 "tell me weather",
 "who are you"
]

extra = []

for x in more_greetings:
    extra.append({"text": x, "intent": "greeting"})

for x in more_other:
    extra.append({"text": x, "intent": "other"})

df2 = pd.concat([df, pd.DataFrame(extra)], ignore_index=True)

df2.to_csv("../data/intent_dataset.csv", index=False)

print("Added extra greeting and other samples")
print("New size:", len(df2))

Added extra greeting and other samples
New size: 348

In [11]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
import joblib

# Paths
intent_path = Path("../data/intent_dataset.csv")
Path("../backend/models").mkdir(parents=True, exist_ok=True)

# Load
df = pd.read_csv(intent_path)
df = df.dropna()

# Split
X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["intent"],
    test_size=0.2, random_state=42, stratify=df["intent"]
)

# Train model
intent_model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=1)),
    ("clf", LinearSVC())
])

intent_model.fit(X_train, y_train)
pred = intent_model.predict(X_test)

print("=== INTENT MODEL REPORT ===")
print(classification_report(y_test, pred, zero_division=0))

# Save joblib
joblib.dump(intent_model, "../backend/models/intent_model.joblib")
print("✅ Saved: ../backend/models/intent_model.joblib")

=== INTENT MODEL REPORT ===
              precision    recall  f1-score   support

check_answer       0.93      1.00      0.97        14
     explain       0.95      1.00      0.98        20
    greeting       1.00      0.80      0.89         5
       other       1.00      0.67      0.80         3
        quiz       1.00      1.00      1.00        14
   recommend       1.00      1.00      1.00        14

    accuracy                           0.97        70
   macro avg       0.98      0.91      0.94        70
weighted avg       0.97      0.97      0.97        70

✅ Saved: ../backend/models/intent_model.joblib

In [12]:
import pandas as pd

df = pd.read_csv("../data/intent_dataset.csv")

more_greetings = [
 "hi","hello","hey","hii","hiii","hai",
 "good morning","good afternoon","good evening",
 "hello tutor","hey tutor","hi tutor","hello ai",
 "greetings","yo","sup","what's up","whats up",
 "how are you","hey there","hi there"
]

extra = pd.DataFrame([{"text": x, "intent": "greeting"} for x in more_greetings])

df2 = pd.concat([df, extra], ignore_index=True)
df2.to_csv("../data/intent_dataset.csv", index=False)

print("✅ Added greetings. New dataset size:", len(df2))

✅ Added greetings. New dataset size: 369